GET http://localhost:4000/authors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwicm9sZSI6InZpZXdlciIsImlhdCI6MTc3MDg4NDM2NiwiZXhwIjoxNzcwODg0OTY2fQ.3oyr9tDcXavIJAsH3vrIWrlQXJ9ZXMMNYYj_DaHLiB0