POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "name": "Example 2",
  "surname": "Example 2",
  "email": "example2@example.com",
  "password": "Example123!@#",
  "role": "viewer"
}