GET http://localhost:4000/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwicm9sZSI6InZpZXdlciIsImlhdCI6MTc3MTI0NDQyMSwiZXhwIjoxNzcxMjQ1MDIxfQ.wvYK2gD1bfCp6fkK3r8h1cFTcu1xNhUMUSqbxY2vGjY