POST http://localhost:4000/books/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwicm9sZSI6InZpZXdlciIsImlhdCI6MTc3MTI0MjE3NywiZXhwIjoxNzcxMjQyNzc3fQ.nX5MXbRi-1XAGVwxWde99bWqBdFUSO8FzLLiZFGNmh4

{
  "title": "Example book 2",
  "authorId": 2,
  "publicationDate": "2025-01-10",
  "numberOfPages": 455,
  "language": "en"
}